export interface MeliProductDetail {
  id: string;
  meli_item_id: string;
  seller_id?: number;
  sku?: string;
  categoryId: string;
  category_id: string;
  category_name?: string;
  category_path: { id: string; name: string }[];
  title: string;
  description?: string;
  price: number;
  base_price?: number;
  original_price?: number | null;
  currency: string;
  stock: number;
  available_quantity: number;
  soldQuantity: number;
  sold_quantity: number;
  status: string;
  condition: string;
  condition_type: string;
  permalink: string;
  thumbnail: string;
  pictures: string[];
  sellerSku?: string;
  brand?: string;
  model?: string;
  gtin?: string;
  attributes: unknown[];
  warranty?: string;
  listing_type_id?: string;
  buying_mode?: string;
  catalog_listing: boolean;
  domain_id?: string;
  video_id?: string | null;
  logistic_type?: string;
  shipping_mode?: string;
  freeShipping: boolean;
  free_shipping: boolean;
  local_pick_up: boolean;
  has_variations: boolean;
  variations: unknown[];
  health: number;
  lastUpdated: string;
  raw_payload: unknown;
  last_webhook_at: string | null;
  last_seen_at: string;
  created_at?: string;
  updated_at: string;
}
